### ISSUE TITLE
[vite]: Rollup failed to resolve import "lodash" from "blog/resources/js/bootstrap.js"

### ISSUE THREAD

**Issue by alisalehi1380** [minhajul/blog#37]
![image](https://github.com/user-attachments/assets/7d3e922d-e5d3-42ea-a306-72629b3e4f93)

<hr />

i fixed it by `npm i lodash`

<br>

![image](https://github.com/user-attachments/assets/54f6e9d2-61a0-4551-82d8-234a640ffef9)

**Comment by minhajul** [comment]
@alisalehi1380 I am closing this issue.
